### ISSUE TITLE
Something about your codes

### ISSUE THREAD

**Issue by Bobhu1995** [harshit2997/Standard-and-Chaotic-Firefly-Algorithm#1]
Dear harshit2997 ：
         I met something wrong  when I run your codes on my PC . I use MATLAB 2017b and I cannot run main_cfa_cont_2.m . It  shows an error：error main_cfa_cont_2 (line 29). Can you help me ?
         Thanks for your reading. Hope you have a good day.

**Comment by Bobhu1995** [comment]
error：Undefined function or variable 'smod'.

**Comment by harshit2997** [comment]
Hello, it is an objective function file that is missing. I'll upload it in
a few hours.

**Comment by Bobhu1995** [comment]
Thank you very much ！
